config/routes.rb
Rails.application.routes.draw do
   devise_for :accounts
	 get "logout", to: 'sessions#destroy', as: 'logout'
   root 'welcome#index'
   get "/dashboard" => "accounts#index"
   get "profile/:username" => "accounts#profile", as: :profile
   resources :posts, only: [:new, :create, :show]
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, ImageUploader
  has_many :posts

  def full_name
  	"#{first_name} #{last_name}"
  end

  def total_followers
  	0
  end

  def total_following
  	1
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	 mount_uploader :image, ImageUploader
	 belongs_to :account
	 before_create :set_active
	 scope :active, -> { where active: true}

	 def set_active
	 	self.active = true
	 end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :authenticate_account!
	before_action :set_account, only: [:profile]

	def index
		@posts = Post.active
	end

	def profile
		
	end

	def set_account
		@account = Account.find_by_username(params[:username])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :email, :password])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def index
end
 
def new
	@post = Post.new
end

def create
	@post = Post.new(post_params)
  @post.account_id = current_account.id if account_signed_in?
	if @post.save
		redirect_to dashboard_path, flash: {success: "Post was created Successfully!" }
	else
		redirect_to new_post_path, flash: {danger: "Post was not saved!"}
  end
end


  def show
  		
  end

  def post_params
  	params.require(:post).permit(:image, :image_cache)  		
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  		
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<% @posts.each do |post|%>
				<div class="post">
					<div class="post-meta">	
						<%= post.account.username%>
					 </div>
						<%= image_tag post.image.url, class: "img img-fluid"%>
				</div>
			<%end%>
		</div>
		<div class="col-md-4">
			<div class="account-summary">
				<p><strong><%= current_account.username%></strong><br/>
				<%= current_account.full_name%></p>
			</div>
			<div class="follower-suggestions">
				
			</div>
		</div>
	</div>
</div>

app/views/accounts/profile.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">

		</div>
		<div class="col-md-8 text-left">
			<h1><%= @account.full_name%></h1>
			<div class="profile-starts"><p><%= @account.posts.count%>posts</p></div>
			<div class="profile-starts"><p><%= @account.posts.total_followers%>follwers</p></div>
			<div class="profile-starts"><p><%= @account.posts.total_following%>following</p></div>
		</div>
	</div>
</div> 

app/views/layouts/_account_nav.html.erb
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <form class="center-search navbar-form navbar-left">
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Search">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Home", dashboard_path %></li>
    <li><%= link_to "New Post", new_post_path %></li>
    <li><%= link_to "MyProfile", profile_path(:username)%></li>
    <li><%= link_to "Logout", logout_path %></li>
  </ul>
</div>

app/views/layouts/_public_nav.html.erb
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <form class="center-search navbar-form navbar-left">
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Search">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "SignUp", new_account_registration_path %></li>
    <li><%= link_to "SignIn", new_account_session_path %></li>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThinkGram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">LOGO</a>
        </div>
      <% if account_signed_in? %>
          <%= render "layouts/account_nav"%> 
        <% else %>
          <%= render "layouts/public_nav"%> 
      <% end %>
        <!-- Collect the nav links, forms, and other content for toggling -->
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%= f.file_field :image%>
	<%= f.hidden_field :image_cache%>
	<%= f.submit "Save Post", class: "" %>
<%end%>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render "form"%>

app/views/welcome/index.html.erb
<div class="container">
	<h1>Hello Welcome to the ThinkGRAM</h1>
	<p>please register or signIn to continue.</p>
</div>